### ISSUE TITLE
tactic.py

### ISSUE THREAD

**Issue by khadekirti** [mynlp/ccg2lambda#3]
Why and where is tactic.py used?

**Comment by pasmargo** [comment]
This script tries to load some proving tactics in ccg2lambda/ root directory. If it fails, then a default tactic is used. We use this because we have slightly different tactics when working in Japanese and English languages, but we are trying to remedy this by unifying tactics.

You can see where tactic.py is used by doing:

```
ccg2lambda$ grep "from tactics" */*.py
scripts/abduction_tools.py:from tactics import get_tactics
scripts/semantic_tools.py:from tactics import get_tactics
```

That is, `tactics.py` is used in `scripts/abduction_tools.py` and `scripts/semantic_tools.py`.
